server:
  port: 8010
  # http://cloud.spring.io/spring-cloud-gateway/single/spring-cloud-gateway.html#_tls_ssl
#  ssl:
#    enabled: true
#    key-alias: scg
#    key-store-password: scg1234
#    key-store: classpath:scg-keystore.p12
#    key-store-type: PKCS12
  
# spring application yaml file
spring:
  jmx:
    enabled: false
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            #allowedOrigins: localhost
            allowedMethods:
              - POST
              - GET
              - OPTIONS
              - DELETE
              - PUT
              - PATCH
            allowedHeaders: 
              - Origin
              - Accept
              - X-Requested-With
              - Content-Type
              - Access-Control-Request-Method
              - Access-Control-Request-Headers
              - Authorization
            allowCredentials: true
            maxAge: 3600
      #default-filters:
        #- SecureHeaders
        #- Hystrix=default
      # http://cloud.spring.io/spring-cloud-gateway/single/spring-cloud-gateway.html#_tls_ssl
      httpclient:
        ssl:
          # Using an insecure trust manager is not suitable for production.
          useInsecureTrustManager: true
          #trustedX509Certificates:
          #  - cert1.pem
          #  - cert2.pem
      routes:
        - id: httpbin-rewrite
          uri: http://httpbin.org
          predicates:
            - Path=/httpbin/**
          filters:
            - RewritePath=/httpbin/(?<segment>.*), /anything/$\{segment}
         
        #- id: httpbin-simple
        #  uri: http://httpbin.org
        #  predicates:
        #    - Path=/httpbin/{id_todo}
        #  filters:
        #    - SetPath=/anything/{id_todo}
        #    
        #- id: httpbin-composite
        #  uri: http://httpbin.org
        #  predicates:
        #    - Path=/httpbin/{id_todo}/tests/{id_test}
        #  filters:
        #    - SetPath=/anything/{id_todo}/tests/{id_test}
            
        - id: todos-route
          uri: http://localhost:8020
          predicates:
            - Path=/todos/**
          filters:
            - RewritePath=/todos/(?<segment>.*), /todos/$\{segment}
            
        - id: profile-todos-route
          uri: http://localhost:8020
          predicates:
            - Path=/profile/todos/**
          filters:
            - RewritePath=/profile/todos/(?<segment>.*), /profile/todos/$\{segment}
          
        #- id: todos-testes-route
        #  uri: http://localhost:8020
        #  predicates:
        #    - Path=/todos/{id_todo}/tests/{id_test}
        #  filters:
        #    - SetPath=/todos/{id_todo}/tests/{id_test}

logging:
  level:
    #root: DEBUG
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG


management.endpoints.web.exposure.include: "*"

#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000
