metadata:
  name: ${project.artifactId}
data:
  application.yml: |
    # spring application yaml file
    spring:
      jpa:
        hibernate:
          ddl-auto: update
        database-platform: org.hibernate.dialect.PostgreSQL9Dialect
        properties:
        #  hibernate.temp.use_jdbc_metadata_defaults: false
          hibernate.jdbc.lob.non_contextual_creation: true
      datasource:
        url: jdbc:postgresql://todo-service-db-postgresql:5432/todo-db
        username: todo-user
        # SECRET_PASSWORD especificada no descritor deployment.yml
        password: ${DB_SECRET_PASSWORD}
        driver-class-name: org.postgresql.Driver
