metadata:
  name: ${project.artifactId}
data:
  application.yml: |
    # spring application yaml file
    api:
      ratelimiter:
        redis:
          cluster:
            master:
              host-name: api-gateway-rate-limit-db-redis-master
            slaves:
            - hots-name: api-gateway-rate-limit-db-redis-slave
              port: 6379
          
    spring:
      cloud:
        gateway:
          routes:
          - id: requestratelimiter_route
            uri: http://todo-service:8080/todos/
            predicates:
            - Path=/todos/{segment}
            filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
