metadata:
  name: ${project.artifactId}
data:
  application.yml: |
    # spring application yaml file
    spring:
      cloud:
        gateway:
          routes:
          - id: requestratelimiter_route
            uri: http://todo-service:8080/todos
            predicates:
            - Path=/todos/{segment}
            filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20


